version: "3.9"
services:
  api:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=api
      - DB_USER=user
      - DB_PASSWORD=secret
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=api
    ports:
      - '5432:5432'